#!/usr/bin/env python3
"""Emit paper/numbers.tex from result files.

Every statistic quoted in a write-up is a LaTeX macro whose value is read from
a results/ JSON or JSONL file, never hand-typed. Register macros in build():

    macro("accSeedZero", lambda: fmt(A["ev0"]["test_accuracy"], 1, pct=True))

Missing fields are emitted as visible ??MISSING?? placeholders and reported
(exit 1), so a stale result file can never silently produce a wrong number.

    python scripts/make_numbers.py [--repo PATH] [--out PATH]

Defaults: repo = parent of this script's directory; out = <repo>/paper/numbers.tex.
"""

import argparse
import json
import sys
from pathlib import Path


def load(repo: Path, rel: str):
    p = repo / rel
    if p.suffix == ".jsonl":
        return [json.loads(line) for line in p.open()]
    return json.load(p.open())


def fmt(x, nd=None, pct=False):
    if pct:
        x = x * 100.0
    if nd is not None:
        x = round(x, nd)
    if isinstance(x, float) and x == 0:
        return "-0.0" if str(x).startswith("-") else "0.0"
    return f"{x:g}"


def ensure_math(s: str) -> str:
    return "\\ensuremath{%s}" % s if any(c in s for c in "-.0123456789") else s


def build(repo: Path):
    """Return {macro_name: (producer, is_text)}. producer() reads from the
    loaded result files and returns a string; is_text=True skips math wrapping."""
    A = {
        # "ev0": load(repo, "results/seed0/evaluation.json"),
    }
    N = {}

    def macro(name, producer, text=False):
        N[name] = (producer, text)

    # macro("accSeedZero", lambda: fmt(A["ev0"]["test_accuracy"], 1, pct=True))
    return N


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()
    out = args.out or args.repo / "paper" / "numbers.tex"
    out.parent.mkdir(parents=True, exist_ok=True)

    N = build(args.repo)
    lines = ["% AUTO-GENERATED by scripts/make_numbers.py -- do not edit by hand."]
    missing = []
    for name, (producer, text) in N.items():
        try:
            val = producer()
            body = val if text else ensure_math(val)
        except Exception as e:  # noqa: BLE001
            missing.append((name, repr(e)))
            body = r"\textbf{??MISSING??}"
        lines.append(rf"\newcommand{{\{name}}}{{{body}}}")
    out.write_text("\n".join(lines) + "\n")

    print(f"wrote {out} ({len(N)} macros)")
    if missing:
        print(f"\n{len(missing)} MISSING -- fix before using:", file=sys.stderr)
        for name, err in missing:
            print(f"  \\{name}: {err}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
